DDCMinOrder = dsp.DigitalDownConverter(...
  'SampleRate',23.328e9,...
  'DecimationFactor',1,...
  'Bandwidth',1.5e9,...
  'PassbandRipple',0.05,...
  'StopbandAttenuation',60,...
  'StopbandFrequencySource', 'Property',...
  'StopbandFrequency',18.75e3,...
  'CenterFrequency',455e3);
